version: "3"

services:
  fastify-app:
    container_name: fastify-app-prod
    image: fastify-app-prod
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - APP_HOST=0.0.0.0
    ports:
      - 8080:8000
